pipeline{
    agent{
        docker{
            image 'python:2.7.16-slim'
        }        
    }
    
    stages{
        stage('build'){
            when{
                 changeset "**/vote/**"
            }
            steps{
                echo 'compiling vote app'
                dir('vote'){
                    sh 'pip install -r requirement.txt'
                }
            }
        }
         stage('test'){
            when{
                 changeset "**/vote/**"
            }
            steps{
                echo 'Running Unit Test on vote app'
                dir('vote'){
                   sh 'nosetests -v'
                }
            }
        }
    }

    post{
        always{
            echo 'Pipeline for vote is completes'
        }
    }
}