pipeline{
    agent none
   
    stages{
        agent{
            docker{
                image 'python:2.7.16-slim'
                args '--user root'
            }        
        }
        stage('build'){
            when{
                 changeset "**/vote/**"
            }
            steps{
                echo 'compiling vote app'
                dir('vote'){
                    sh 'pip install -r requirement.txt'
                }
            }
        }
         stage('test'){
            agent{
                docker{
                    image 'python:2.7.16-slim'
                    args '--user root'
                }        
            }
            when{
                 changeset "**/vote/**"
            }
            steps{
                echo 'Running Unit Test on vote app'
                dir('vote'){
                    sh 'pip install -r requirement.txt'
                    sh 'nosetests -v'
                }
            }
        }
        stage('docker-package'){
            agent any
            when{
                 changeset "**/vote/**"
                 branch 'master'
            }
            steps{
                echo 'packaging vote app with docker'
                script{
                    docker.withRegistry('https://index.docker.io/v1/', 'dockerlogin') {
                         def workerImage = docker.build("semimatadocker/vote:v${env.BUILD_ID}", "./vote")
                         workerImage.push()
                         workerImage.push("${env.BRANCH_NAME}")
                    }

                }
            }
        }
    post{
        always{
            echo 'Pipeline for vote is completes'
        }
    }
}