pipeline{
    agent any

    tools{
        maven 'Maven 3.6.3'
    }
    
    stages{
        stage('build'){
            steps{
                echo 'compiling worker app'
                dir('worker'){
                    sh 'mvn compile'
                }
            }
        }
         stage('test'){
            steps{
                echo 'Running Unit Test on worker app'
                sleep 15
            }
        }
         stage('package'){
            steps{
                echo 'packaging worker app'
                sleep 15
            }
        }

    }
    
    post{
        always{
            echo 'Build pipeline for worker is completed'
        }
    }
}